FROM apache/airflow:2.8.1-python3.9

USER airflow

WORKDIR /opt/airflow

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Initialize Airflow DB (only once)
RUN airflow db init
RUN airflow users create --username admin --password admin --firstname John --lastname Doe --role Admin --email admin@example.com

# Expose necessary ports for webserver (if not using docker-compose ports)
EXPOSE 8080
